// <auto-generated />
namespace TicketSystemApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class TicketCreatedChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TicketCreatedChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201912112215397_TicketCreatedChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
